Controllers/MeEmployeeTrainingController.cs
using HRTool.CommanMethods.Resources;
using HRTool.DataModel;
using Microsoft.AspNet.Identity;
using HRTool.Models.Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRTool.CommanMethods.Settings;
using System.Web.Script.Serialization;
using System.Configuration;
using System.IO;
using HRTool.CommanMethods;

namespace HRTool.Controllers
{
    [CustomAuthorize]
    public class MeEmployeeTrainingController : Controller
    {

        #region const
        EmployeeTrainingMethod _EmployeeTrainingMethod = new EmployeeTrainingMethod();
        EmployeeMethod _employeeMethod = new EmployeeMethod();
        OtherSettingMethod _otherSettingMethod = new OtherSettingMethod();
        #endregion

        //
        // GET: /EmployeeTraining/
        public ActionResult Index(int EmployeeId)
        {
            EmployeeTrainingViewModel model = new EmployeeTrainingViewModel();
            model.CurrentUserId = EmployeeId;
            return View(model);
        }
        public List<EmployeeTrainingViewModel> returnList()
        {
            List<EmployeeTraining> data = _EmployeeTrainingMethod.getAllList().Where(x=>x.EmployeeId == SessionProxy.UserId).ToList();
        //    List<EmployeeTraining> data = _EmployeeTrainingMethod.getAllListByEmployee(Id).ToList();
            List<EmployeeTrainingViewModel> model = new List<EmployeeTrainingViewModel>();
            foreach (var item in data)
            {
                var employeeName = _employeeMethod.getEmployeeById(item.EmployeeId);
                string Name = string.Format("{0} {1}", employeeName.FirstName, employeeName.LastName);
                EmployeeTrainingViewModel training = new EmployeeTrainingViewModel();
                training.Id = item.Id;
                training.EmployeeName = Name;
                if (item.TrainingNameId != null)
                {
                    training.TrainingName = _EmployeeTrainingMethod.getTrainingById(Convert.ToInt32(item.TrainingNameId));
                }
                if (item.Id != null)
                {
                    training.ImportanceName = _EmployeeTrainingMethod.GetImportnceNameById(Convert.ToInt32(item.Id));
                }
                if (item.Status != 0)
                {
                    training.StatusName = _EmployeeTrainingMethod.getTrainingStatusById(Convert.ToInt32(item.Status));
                }
                else
                {
                    training.StatusName = "";
                }
                training.Progress = item.Progress;
                training.StartDate = String.Format("{0:dd-MMM-yyy}", item.StartDate);
                training.EndDate = String.Format("{0:dd-MMM-yyy}", item.EndDate);
                training.ExpiryDate = String.Format("{0:dd-MMM-yyy}", item.ExpiryDate);
                model.Add(training);
            }
            return model;
        }
        public ActionResult List()
        {
            List<EmployeeTrainingViewModel> model = returnList();
            return PartialView("_PartialTrainingList", model);
        }
        public ActionResult SavData(EmployeeTrainingViewModel model)
        {
            int userId = SessionProxy.UserId;
            model.CurrentUserId = userId;
            JavaScriptSerializer js = new JavaScriptSerializer();
            model.ListDocument = js.Deserialize<List<AdminTraningDocumentViewModel>>(model.TraingDocumentList);
            _EmployeeTrainingMethod.SaveTrainingdSet(model, userId);
            List<EmployeeTrainingViewModel> modelList = returnList();
            return PartialView("_PartialTrainingList", modelList);
        }
        public ActionResult AddEditTrainingSet(int Id, int EmployeeId)
        {
            EmployeeTrainingViewModel model = new EmployeeTrainingViewModel();
            model.Id = Id;
            if (Id > 0)
            {
                var hr_Training = _EmployeeTrainingMethod.GetTrainingListById(Id);
                
                var Status = _EmployeeTrainingMethod.getTrainingStatusById(Convert.ToInt32(hr_Training.Status));
                model.BindEmployeeList = _EmployeeTrainingMethod.GetEmployeeList(hr_Training.EmployeeId);
                var Training = _otherSettingMethod.getAllSystemValueListByKeyName("Training List");
                foreach (var item in Training)
                {
                    if (item.Id == hr_Training.TrainingNameId)
                    {
                        model.BindTrainingList.Add(new SelectListItem() { Text = @item.Value, Value = @item.Id.ToString(), Selected = true });
                    }
                    else
                    {
                        model.BindTrainingList.Add(new SelectListItem() { Text = @item.Value, Value = @item.Id.ToString() });
                    }
                }
                var TrainingStatus = _otherSettingMethod.getAllSystemValueListByKeyName("Traning Status List");
                foreach (var item in TrainingStatus)
                {
                    if (item.Value == Status)
                    {
                        model.BindTrainingStatusList.Add(new SelectListItem() { Text = @item.Value, Value = @item.Id.ToString(), Selected = true });
                        
                    }
                    else
                    {
                        model.BindTrainingStatusList.Add(new SelectListItem() { Text = @item.Value, Value = @item.Id.ToString() });
                        
                    }

                   ;
                    
                }

                model.Description = hr_Training.Description;
                model.Importance = hr_Training.Importance;
                model.Progress = hr_Training.Progress;
                model.StartDate = String.Format("{0:dd-MM-yyy}", hr_Training.StartDate);
                model.EndDate = String.Format("{0:dd-MM-yyy}", hr_Training.EndDate);
                model.ExpiryDate = String.Format("{0:dd-MM-yyy}", hr_Training.ExpiryDate);
                model.Provider = hr_Training.Provider;
                model.Cost = hr_Training.Cost;
                model.Notes = hr_Training.Notes;
                var TraingDoument = _EmployeeTrainingMethod.getTrainigDocumentByCaseId(Id);
                foreach (var item in TraingDoument)
                {
                    AdminTraningDocumentViewModel docModel = new AdminTraningDocumentViewModel();
                    docModel.Id = item.Id;
                    docModel.originalName = item.OriginalName;
                    docModel.newName = item.NewName;
                    docModel.description = item.Description;
                    model.ListDocument.Add(docModel);
                }
            }
            else
            {
                model.BindEmployeeList = _EmployeeTrainingMethod.GetEmployeeList(EmployeeId);
                var hr_Training = _EmployeeTrainingMethod.GetStatusNameById(EmployeeId);
                var Training = _otherSettingMethod.getAllSystemValueListByKeyName("Training List");
                model.BindTrainingList.Add(new SelectListItem() { Text = "-- Select Training --", Value = "0" });

                foreach (var item in Training)
                {
                    model.BindTrainingList.Add(new SelectListItem() { Text = @item.Value, Value = @item.Id.ToString() });
                }
                var TrainingStatus = _otherSettingMethod.getAllSystemValueListByKeyName("Traning Status List");
                foreach (var item in TrainingStatus)
                {
                    
                        model.BindTrainingStatusList.Add(new SelectListItem() { Text = @item.Value, Value = @item.Id.ToString(), Selected = true });
                    
                }
            }
            return PartialView("_PartialTrainingAddSet", model);

        }
        public ActionResult DeleteTrainingRecord(int Id)
        {
            int userId = SessionProxy.UserId;
            _EmployeeTrainingMethod.DeleteTraining(Id, userId);
            List<EmployeeTrainingViewModel> modelList = returnList();
            return PartialView("_PartialTrainingList", modelList);
        }
        public ActionResult FiledTypeList()
        {
            FiledViewModel model = new FiledViewModel();
            var AssetsTypeList = _otherSettingMethod.getAllSystemValueListByKeyName("Field Type List");
            foreach (var item in AssetsTypeList)
            {
                model.BindFiledTypeList.Add(new SelectListItem() { Text = @item.Value, Value = @item.Id.ToString() });
            }
            return PartialView("_PartialAdminFiledType", model);
        }

        [HttpPost]
        public ActionResult ImageData()
        {
            string FilePath = string.Empty;
            string fileName = string.Empty;
            string originalFileName = string.Empty;
            if (Request.Files.Count > 0)
            {
                FilePath = ConfigurationManager.AppSettings["AdminTraining"].ToString();
                HttpPostedFileBase hpf = Request.Files[0] as HttpPostedFileBase;
                originalFileName = hpf.FileName;
                fileName = string.Format("{0}_{1}{2}", Path.GetFileNameWithoutExtension(hpf.FileName), DateTime.Now.ToString("ddMMyyyyhhmmss"), Path.GetExtension(hpf.FileName));
                string path = Path.Combine(HttpContext.Server.MapPath(FilePath), fileName);
                hpf.SaveAs(path);
            }

            return Json(new { originalFileName = originalFileName, NewFileName = fileName });
        }
    }
}

Views/MeEmployeeTraining/Index.cshtml
@model HRTool.Models.Resources.EmployeeTrainingViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MeLayout.cshtml";
}

<div id="page_content_inner">
    <input type="hidden" id="CurrentUser" value="@Model.CurrentUserId" />
    <h1 class="page-title">
        Training Matrix
        <small>Check the progress of each Resource in your team's training programs</small>
    </h1>
     
        
            <div id="tableDivTraining">
                @Html.Action("List", "MeEmployeeTraining", new { id = @Model.CurrentUserId })
        
    </div>
</div>
<script src="~/JS/Resources/Training/EmployeeTrainingJS.js"></script>
<script>
    var constantSet = {
        Savetraining: '@Url.Action("SavData", "MeEmployeeTraining")',
        addEdit: '@Url.Action("AddEditTrainingSet", "MeEmployeeTraining")',
        DeleteProjectUrl: '@Url.Action("DeleteTrainingRecord", "MeEmployeeTraining")',
        FiledTypelistUrl: '@Url.Action("FiledTypeList", "MeEmployeeTraining")',
        ImageUrl: '@Url.Action("ImageData", "MeEmployeeTraining")',
    };
</script>

Views/MeEmployeeTraining/_PartialFiledType.cshtml
@model HRTool.Models.Resources.FiledViewModel

<div class="row marbot10">
    <div class="col-md-3">
        <label class="control-label" for="systemListName">Filed Type*</label>
    </div>
    <div class="col-md-6 dropdown-selectlist" data-toggle="tooltip" data-placement="right" title=" Select General Skills this Project represents">
        <select class="form-control" id="drp-FiledType">
            @foreach (var FiledType in Model.BindFiledTypeList)
            {
                <option value="@FiledType.Value">@FiledType.Text</option>
            }
        </select>
    </div>
    <div class="col-md-4">
    </div>
</div>
<div class="row marbot10">
    <div class="form-group">
        <label class="col-md-3">Lable*</label>
        <div class="col-md-6" data-toggle="tooltip" data-placement="right" title=" Values Of the Cost">
            <input type="text" placeholder="Label for text field" id="Labletext" name="label" class="form-control ng-pristine ng-invalid ng-invalid-required ng-touched"></input>
        </div>
        <div class="col-md-3">
            <span class="field-validation-error" id="validationmessageName" data-valmsg-for="Name" data-valmsg-replace="true" style="display:none"></span>
        </div>
    </div>
</div>
<div class="row marbot10 AdddrpCustome" style="display:none">
    <div class=" form-group" data-id="0">
        <label class="col-md-3">Note</label>
        <div class="col-md-6">
            <textarea class="form-control" id="Additemlist" placeholder="Item for Drop Down like i.e abc,abc,"></textarea>
        </div>
        <div class="col-md-3">
            <span class="field-validation-error" id="validationmessageName" data-valmsg-for="Name" data-valmsg-replace="true" style="display:none"></span>
        </div>
    </div>
</div>
<div class="row marbot10">
    <div class="form-group">
        <label class="col-md-3">Mandatory</label>
        <div class="col-md-6" data-toggle="tooltip" data-placement="right" title=" Values Of the Cost">
            <input type="checkbox" class="ng-valid ng-dirty ng-valid-parse ng-touched">
        </div>
        <div class="col-md-3">
            <span class="field-validation-error" id="validationmessageName" data-valmsg-for="Name" data-valmsg-replace="true" style="display:none"></span>
        </div>
    </div>
</div>

Views/MeEmployeeTraining/_PartialTrainingAddSet.cshtml
@model HRTool.Models.Resources.EmployeeTrainingViewModel

<div id="wizard" class="swMain">
    <ul class="tablistnew two">
        <li class="active">
            <a href="#step-1" class="s1">
                <span>1</span>Details
            </a>
        </li>
        <li>
            <a href="#step-2" class="s2">
                <span>2</span>Comment
            </a>
        </li>
    </ul>

    @*<ul class="nav nav-tabs">
            <li class="active">
                <a href="#step-1" class="s1">
                    <span>1</span>Details
                </a>
            </li>
            <li>
                <a href="#step-2" class="s2">
                    <span>2</span>Comment
                </a>
            </li>
        </ul>*@
    <div id="step-1">
        <div class="row marbot10">
            <div class="form-group">
                <label class="col-md-3">Employee-SSO*</label>
                <input type="hidden" id="hidden-Id" value="@Model.Id" />
                <input type="hidden" id="CutomiseFiled" value="@Model.CustomFieldsJSON" />
                <div class="col-md-6" data-toggle="tooltip" data-placement="right" title=" Select Location">
                    <select class="form-control" id="EmployeeId" disabled>
                        @foreach (var Employee in Model.BindEmployeeList)
                        {
                            <option value="@Employee.Value" @(Employee.Selected ? "Selected" : "")>@Employee.Text</option>
                        }
                    </select>
                </div>
                <div class="col-md-3">
                    <span class="field-validation-error" id="validationmessageEmployeeName" data-valmsg-for="Name" data-valmsg-replace="true" style="display:none"></span>
                </div>
            </div>
        </div>
        <div class="row marbot10">
            <div class="col-md-3">
                <label class="control-label" for="systemListName">Training*</label>
            </div>
            <div class="col-md-6 dropdown-selectlist" data-toggle="tooltip" data-placement="right" title=" Select General Skills this Project represents">
                <select class="form-control" id="drp-Training">
                    @foreach (var BindTrainingList in Model.BindTrainingList)
                    {
                        <option value="@BindTrainingList.Value" @(BindTrainingList.Selected ? "Selected" : "")>@BindTrainingList.Text</option>
                    }
                </select>
            </div>
            <div class="col-md-3">
                <span class="field-validation-error" id="validationmessageTrainingId" data-valmsg-for="Name" data-valmsg-replace="true" style="display:none"></span>
            </div>
        </div>
        <div class="row marbot10">
            <div class="form-group">
                <label class="col-md-3">Description</label>
                <div class="col-md-6">
                    <textarea class="form-control" id="txt-SystemListDescription" value="@Model.Description" placeholder="Description" data-toggle="tooltip" name="Description" data-placement="right" title="" data-original-title="Skill Description">@Model.Description</textarea>
                </div>
                <div class="col-md-3">
                    <span class="field-validation-error" id="validationmessageName" data-valmsg-for="Name" data-valmsg-replace="true" style="display:none"></span>
                </div>
            </div>
        </div>
        <div class="row marbot10">
            <div class="form-group">
                <label class="col-md-3">Importance*</label>
                <div class="col-md-6">
                    <div class="resource-report-radio-btn">
                        @if (Model.Importance == 1)
                        {
                            <label class="radio-btn">
                                <input type="radio" name="Importance" id="MandatoryId" value="1" checked>
                                <span>Mandatory</span>
                            </label>
                                <label class="radio-btn">
                                    <input type="radio" name="Importance" id="OptionalId" value="0">
                                    <span>Optional</span>
                                </label>
                        }
                        else if (Model.Importance == 0)
                        {
                            <label class="radio-btn">
                                <input type="radio" name="Importance" id="MandatoryId" value="1">
                                <span>Mandatory</span>
                            </label>
                                <label class="radio-btn">
                                    <input type="radio" name="Importance" id="OptionalId" value="0" checked>
                                    <span>Optional</span>
                                </label>
                        }
                        else
                        {
                            <label class="radio-btn">
                                <input type="radio" name="Importance" id="MandatoryId" value="1">
                                <span>Mandatory</span>
                            </label>
                                <label class="radio-btn">
                                    <input type="radio" name="Importance" id="OptionalId" value="0">
                                    <span>Optional</span>
                                </label>
                        }

                    </div>
                </div>
                <div class="col-md-3">
                    <span class="field-validation-error" id="validationmessageImportance" data-valmsg-for="Name" data-valmsg-replace="true" style="display:none"></span>
                </div>
            </div>
        </div>
        <div class="row marbot10">
            <div class="col-md-3">
                <label class="control-label" for="systemListName">Status</label>
            </div>
            <div class="col-md-6 dropdown-selectlist" data-toggle="tooltip" data-placement="right" title=" Select General Skills this Project represents">
                <select class="form-control" id="drp-TrainingStatus">
                   
                    @foreach (var Status in Model.BindTrainingStatusList)
                    {
                        <option value="@Status.Value" @(Status.Selected ? "Selected" : "")>@Status.Text</option>
                    }
                </select>
            </div>
            <div class="col-md-4">
            </div>
        </div>

        @if (Model.Progress == null)
            {
            <div class="row marbot10" id="Progresshideshow" style="display:none">
                <div class="form-group">
                    <label class="control-label col-md-3">Progress</label>
                    <div class="col-md-6">
                        <input type="hidden" id="Progress">
                        <input type="text" id="example_id" name="example_name" value="" />
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="row marbot10" id="Progresshideshow">
                <div class="form-group">
                    <label class="control-label col-md-3">Progress</label>
                    <div class="col-md-6">
                        <input type="hidden" id="Progress">
                        <input type="text" id="example_id" name="example_name" value="@Model.Progress" />
                    </div>
                </div>
            </div>
        }
        <div class="row marbot10">
            <div class="form-group">
                <label class="control-label col-md-3">Start Date*</label>
                <div class="col-md-6">
                    <input type="text" class="form-control mrg-btm datepicker" id="StartDate" placeholder="Start Date" value="@Model.StartDate" name="StartDate" title="Start Date">
                </div>

                <div class="col-md-3">
                    <span class="field-validation-error" id="validationmessageStartDate" data-valmsg-for="StartDate" data-valmsg-replace="true" style="display:none"></span>
                </div>
            </div>
        </div>
        <div class="row marbot10">
            <div class="form-group">
                <label class="control-label col-md-3">End Date*</label>
                <div class="col-md-6">
                    <input type="text" class="form-control mrg-btm datepicker" id="EndDate" value="@Model.EndDate" placeholder="End Date" name="EndDate" title="End Date">
                </div>

                <div class="col-md-3">
                    <span class="field-validation-error" id="validationmessageEndDate" data-valmsg-for="EndDate" data-valmsg-replace="true" style="display:none"></span>
                    <span class="field-validation-error" id="lbl-error-GreaterEndDate" data-valmsg-for="EndDate" data-valmsg-replace="true" style="display:none">Please Select Valid End Date.</span>

                </div>
            </div>
        </div>
        <div class="row marbot10">
            <div class="form-group">
                <label class="control-label col-md-3">Expiry Date*</label>
                <div class="col-md-6">
                    <input type="text" class="form-control mrg-btm datepicker" id="ExpiryDate" value="@Model.ExpiryDate" placeholder="Expiry Date" name="ExpiryDate" title="Expiry Date">
                </div>

                <div class="col-md-3">
                    <span class="field-validation-error" id="validationmessageExpiryDate" data-valmsg-for="ExpiryDate" data-valmsg-replace="true" style="display:none"></span>
                    <span class="field-validation-error" id="lbl-error-GreaterExpDate" data-valmsg-for="EndDate" data-valmsg-replace="true" style="display:none">Please Select Valid Expiry Date.</span>

                </div>
            </div>
        </div>
        <div class="row marbot10">
            <div class="form-group">
                <label class="col-md-3">Provider</label>
                <div class="col-md-6" data-toggle="tooltip" data-placement="right" title=" Name Of the Provider">
                    <input type="text" name="Provider" id="Provider" value="@Model.Provider" class="form-control" ng-required="false">
                </div>
                <div class="col-md-3">
                    <span class="field-validation-error" id="validationmessageName" data-valmsg-for="Name" data-valmsg-replace="true" style="display:none"></span>
                </div>
            </div>
        </div>
        <div class="row marbot10">
            <div class="form-group">
                <label class="col-md-3">Cost</label>
                <div class="col-md-6" data-toggle="tooltip" data-placement="right" title=" Values Of the Cost">
                    <input type="number" min="0" name="Cost" id="Cost" value="@Model.Cost" class="form-control" ng-required="false">
                </div>
                <div class="col-md-3">
                    <span class="field-validation-error" id="validationmessageName" data-valmsg-for="Name" data-valmsg-replace="true" style="display:none"></span>
                </div>
            </div>
        </div>
        <div class="row marbot10">
            <div class="form-group">
                <label class="col-md-3">Note</label>
                <div class="col-md-6">
                    <textarea class="form-control" id="Notes" value="@Model.Notes" placeholder="Notes">@Model.Notes</textarea>
                </div>
                <div class="col-md-3">
                    <span class="field-validation-error" id="validationmessageName" data-valmsg-for="Name" data-valmsg-replace="true" style="display:none"></span>
                </div>
            </div>
        </div>

        <div id="CoustomeAdd" class="CustomeFiled">
            <input type="hidden" id="lastId" value="0" />
        </div>

        <button class="md-btn md-btn-primary add-new-timesheet-btn" id="btn_AddNewField" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#AddNewFieldModel">Add New Field</button>
    </div>
    <div id="step-2">
        <div class="browse-attach">
            <label type="file" for="fileToUpload" class="btn btn-sm btn-purple btn-upload md-btn-primary">
                <p>Drop docs,pdfs or images here or click to upload</p>
                <span class="btn">BROWSE</span>
            </label>
            <input type="file" id="fileToUpload" accept=".jpg,.jpeg,.bmp,.png" style="display: none">
        </div>
        <div id="filesList">
            @foreach (var item in Model.ListDocument)
            {
                <div class="row ListData"><div class="col-lg-1 icon"><i class="fa fa-paperclip"></i></div><div class="col-lg-10 attach-disc"><label class="fileName" data-newfilename="@item.newName">@item.originalName</label><br><input type="text" class="ImageDescription form-control" value="@item.description" placeholder="Add Description Here"></div><div class="col-lg-1 file-deleteicon"><i class="fa fa-trash-o"></i></div></div>
            }
        </div>
    </div>
</div>

<script>
    $("#Cost").keypress(function (event) {
        if (event.which != 8 && event.which != 0 && (event.which < 48 || event.which > 57)) {
            return false;
        }
    });
</script>