Models/Admin/AdminDocumentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRTool.Models.Admin
{
    public class AdminDocumentViewModel
    {
        public AdminDocumentViewModel()
        {
            BusinessList = new List<SelectListItem>();
            DivisionList = new List<SelectListItem>();
            PoolList = new List<SelectListItem>();
            FunctionList = new List<SelectListItem>();
            CategoryList = new List<SelectListItem>();
            WorkerList = new List<SelectListItem>();
            ManagerList = new List<SelectListItem>();
            CustomerList = new List<SelectListItem>();
        }
        public Nullable<int> flag { get; set; }
        public string Type { get; set; }
        public int Id { get; set; }
        public string DocumentPath { get; set; }
        public string DocumentOriginalPath { get; set; }
        public string Description { get; set; }
        public string LinkDisplayText { get; set; }
        public string LinkURL { get; set; }
        public int BusinessID { get; set; }
        public string Business { get; set; }
        public int DivisionID { get; set; }
        public string Division { get; set; }
        public int PoolID { get; set; }
        public string Pool { get; set; }
        public int FunctionID { get; set; }
        public string Function { get; set; }
        public int Category { get; set; }
        public string CategoryName { get; set; }
        public bool EmployeeAccess { get; set; }
        public bool ManagerAccess { get; set; }
        public bool CustomerAccess { get; set; }
        public bool SpecificWorker { get; set; }
        public string SpecificWorkerName { get; set; }
        public int? WorkerID { get; set; }
        public bool SpecificManager { get; set; }
        public string SpecificManagerName { get; set; }
        public int? ManagerID { get; set; }
        public bool SpecificCustomer { get; set; }
        public string SpecificCustomerName { get; set; }
        public int? CustomerID { get; set; }
        public bool SignatureRequire { get; set; }
        public string IpAddress { get; set; }

        public string CreateDate { get; set; }
        public IList<SelectListItem> BusinessList { get; set; }
        public IList<SelectListItem> DivisionList { get; set; }
        public IList<SelectListItem> PoolList { get; set; }
        public IList<SelectListItem> FunctionList { get; set; }
        public IList<SelectListItem> CategoryList { get; set; }
        public IList<SelectListItem> WorkerList { get; set; }
        public IList<SelectListItem> ManagerList { get; set; }
        public IList<SelectListItem> CustomerList { get; set; }
    }
}

Controllers/AdminDocumentController.cs
using HRTool.CommanMethods.Admin;
using HRTool.CommanMethods.Resources;
using HRTool.CommanMethods.RolesManagement;
using HRTool.CommanMethods.Settings;
using HRTool.DataModel;
using HRTool.Models.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Configuration;
using System.IO;
using HRTool.CommanMethods;
using static HRTool.CommanMethods.Enums;

namespace HRTool.Controllers
{
    [CustomAuthorize]
    public class AdminDocumentController : Controller
    {
        #region Constant
        EvolutionEntities _db = new EvolutionEntities();
        OtherSettingMethod _otherSettingMethod = new OtherSettingMethod();
        CompanyStructureMethod _CompanyStructureMethod = new CompanyStructureMethod();
        AdminTMSMethod _AdminTMSMethod = new AdminTMSMethod();
        TMSSettingsMethod _TMSSettingsMethod = new TMSSettingsMethod();
        EmployeeMethod _employeeMethod = new EmployeeMethod();
        RolesManagementMethod _RolesManagementMethod = new RolesManagementMethod();
        AdminDocumentMethod _AdminDocumentMethod = new AdminDocumentMethod();
        #endregion
        // GET: /AdminDocument/
        [Authorize]
        public ActionResult Index()
        {
            List<AdminDocumentViewModel> model = new List<AdminDocumentViewModel>();
            var data = _AdminDocumentMethod.getAllDocumentList();
            int EmpId = SessionProxy.UserId;
            var empData = _db.AspNetUsers.Where(x => x.Id == EmpId).FirstOrDefault();
            
            if (data.Count > 0)
            {
                foreach (var details in data)
                {
                    if (!string.IsNullOrEmpty(details.Description) || !string.IsNullOrEmpty(details.DocumentPath))
                    {
                        AdminDocumentViewModel datamodel = new AdminDocumentViewModel();
                        if (empData != null)
                        {
                            if (empData.SSOID.Contains('C'))
                            {
                                datamodel.flag = 1;  
                            }
                        }
                        datamodel.Type = "Document";
                        datamodel.Id = details.Id;
                        datamodel.Description = details.Description;
                        datamodel.DocumentOriginalPath = details.DocumentOriginalPath;
                        datamodel.DocumentPath = details.DocumentPath;
                        datamodel.Category = (int)details.Category;
                        if (details.Category != 0)
                        {
                            var res = _otherSettingMethod.getSystemListValueById((int)details.Category);
                            if(res != null)
                            datamodel.CategoryName = res.Value;
                        }
                        datamodel.BusinessID = (int)details.BusinessID;
                        if (details.BusinessID != 0)
                        {
                            var buz = _CompanyStructureMethod.getBusinessListById((int)details.BusinessID);
                            if(buz != null)
                            {
                                datamodel.Business = buz.Name;
                            }
                        }
                        datamodel.DivisionID = (int)details.DivisionID;
                        if (details.DivisionID != 0)
                        {
                            var div = _CompanyStructureMethod.getDivisionById((int)details.DivisionID);
                            if(div != null)
                            datamodel.Division = div.Name;
                        }
                        datamodel.PoolID = (int)details.PoolID;
                        if (details.PoolID != 0)
                        {
                            var pol = _CompanyStructureMethod.getPoolsListById((int)details.PoolID);
                            if(pol != null)
                            datamodel.Pool = pol.Name;
                        }
                        datamodel.FunctionID = (int)details.FunctionID;
                        if (details.FunctionID != 0)
                        {
                            var fun = _CompanyStructureMethod.getFunctionsListById((int)details.FunctionID);
                            if(fun != null)
                            datamodel.Function = fun.Name;
                        }
                        datamodel.CreateDate = String.Format("{0:dd-MM-yyyy}", details.CreatedDate);
                        model.Add(datamodel);
                    }
                    else if(!string.IsNullOrEmpty(details.LinkDisplayText) || !string.IsNullOrEmpty(details.LinkURL))
                    {
                        AdminDocumentViewModel datamodel = new AdminDocumentViewModel();
                        if (empData != null)
                        {
                            if (empData.SSOID.Contains('C'))
                            {
                                datamodel.flag = 1;
                            }
                        }
                        datamodel.Type = "Link";
                        datamodel.Id = details.Id;
                        datamodel.LinkDisplayText = details.LinkDisplayText;
                        datamodel.LinkURL = details.LinkURL;
                        //datamodel.DocumentPath = details.DocumentPath;
                        datamodel.Category = (int)details.Category;
                        if (details.Category != 0)
                        {
                            var res = _otherSettingMethod.getSystemListValueById((int)details.Category);
                            datamodel.CategoryName = res.Value;
                        }
                        datamodel.BusinessID = (int)details.BusinessID;
                        if (details.BusinessID != 0)
                        {
                            var buz = _CompanyStructureMethod.getBusinessListById((int)details.BusinessID);
                            datamodel.Business = buz.Name;
                        }
                        datamodel.DivisionID = (int)details.DivisionID;
                        if (details.DivisionID != 0)
                        {
                            var div = _CompanyStructureMethod.getDivisionById((int)details.DivisionID);
                            datamodel.Division = div.Name;
                        }
                        datamodel.PoolID = (int)details.PoolID;
                        if (details.PoolID != 0)
                        {
                            var pol = _CompanyStructureMethod.getPoolsListById((int)details.PoolID);
                            datamodel.Pool = pol.Name;
                        }
                        datamodel.FunctionID = (int)details.FunctionID;
                        if (details.FunctionID != 0)
                        {
                            var fun = _CompanyStructureMethod.getFunctionsListById((int)details.FunctionID);
                            datamodel.Function = fun.Name;
                        }
                        datamodel.CreateDate = String.Format("{0:dd-MM-yyyy}", details.CreatedDate);
                        model.Add(datamodel);
                    }
                }

            }

            return View(model);
        }
        public AdminDocumentViewModel returnList(int Id)
        {
            AdminDocumentViewModel datamodel = new AdminDocumentViewModel();
            foreach (var item in _otherSettingMethod.getAllSystemValueListByKeyName("Document Type"))
            {
                datamodel.CategoryList.Add(new SelectListItem() { Text = item.Value, Value = item.Id.ToString() });
            }
            foreach (var item in _CompanyStructureMethod.getAllBusinessList())
            {
                datamodel.BusinessList.Add(new SelectListItem() { Text = item.Name, Value = item.Id.ToString() });

            }
            //foreach (var item in _RolesManagementMethod.GetEmployeesList())
            //{
            //    datamodel.WorkerList.Add(new SelectListItem() { Text = item.FirstName + item.LastName + "-" + item.SSOID, Value = item.Id.ToString() });
            //}
            //foreach (var item in _RolesManagementMethod.GetManagersList())
            //{
            //    datamodel.ManagerList.Add(new SelectListItem() { Text = item.FirstName + item.LastName + "-" + item.SSOID, Value = item.Id.ToString() });
            //}
            //foreach (var item in _RolesManagementMethod.GetCustomerList())
            //{
            //    datamodel.CustomerList.Add(new SelectListItem() { Text = item.FirstName + item.LastName + "-" + item.SSOID, Value = item.Id.ToString() });
            //}
            foreach (var item in _employeeMethod.GetAllResourceEmployeeList().Where(x => x.AspNetUserRoles.Count() > 0 ? x.AspNetUserRoles.FirstOrDefault().RoleId != (int)Roles.SuperAdmin ? x.CreatedBy == SessionProxy.UserId : true : x.CreatedBy == SessionProxy.UserId).ToList())
            {
                datamodel.WorkerList.Add(new SelectListItem() { Text = item.FirstName + item.LastName + "-" + item.SSOID, Value = item.Id.ToString() });
            }
            foreach (var item in _RolesManagementMethod.GetManagersList())
            {
                datamodel.ManagerList.Add(new SelectListItem() { Text = item.FirstName + item.LastName + "-" + item.SSOID, Value = item.Id.ToString() });
            }
            foreach (var item in _employeeMethod.GetAllCoustomerEmployeeList().Where(x => x.AspNetUserRoles.Count() > 0 ? x.AspNetUserRoles.FirstOrDefault().RoleId != (int)Roles.SuperAdmin ? x.CreatedBy == SessionProxy.UserId : true : x.CreatedBy == SessionProxy.UserId).ToList())
            {
                datamodel.CustomerList.Add(new SelectListItem() { Text = item.FirstName + item.LastName + "-" + item.SSOID, Value = item.Id.ToString() });

Views/AdminDocument/Index.cshtml
@model IList<HRTool.Models.Admin.AdminDocumentViewModel>
@using HRTool.CommanMethods;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="DocumentModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title DocumentTitle">Add Document</h4>
            </div>
            <div class="modal-body" id="AddDocumentBody">

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success btn-Add-Edit" id="btn-submit-Document">Add</button>
                <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<h1 class="page-title">
    Document List
    <small>View company documents or upload a new one.</small>
</h1>
 
 <div class="clearfix"></div>

<div class="md-card">
    <div>
        <div class="uk-overflow-container">
           
                <div id="tableDiv">
                   @if(Model.Count > 0)
                   {
                    
                    <div class="table-btns">
                        <a class="btn btn-success btn-circle   btn-add-Document" title="Add Document" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#DocumentModal"><i class="fa fa-plus"></i></a>
                        <a class="btn btn-primary btn-circle   btn-edit-Document" title="Edit" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#DocumentModal" disabled="disabled"><i class="material-icons">edit</i></a>
                        <a class="btn btn-danger btn-circle   btn-delete-Document" data-toggle="tooltip" data-placement="bottom" title="Delete" disabled="disabled"><i class="fa fa-trash-o"></i> </a>
                        <button title="Refresh" class="btn btn-primary btn-circle   btn-Refresh-Document" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-reply"></i></button>
                        <button title="Clear Sorting" class="btn btn-warning btn-circle   btn-ClearSorting-Document" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-upload"></i></button>
                        <button class="btn btn-info btn-circle   btn-clearFilter-Document" data-toggle="tooltip" data-placement="bottom" title="Clear Filter"><i class="fa fa-filter"></i></button>
                    </div>
                    
                   }
                   else
                   {
                        <div class="table-btns 11">
                            <a class="btn btn-success btn-circle   btn-add-Document" title="Add Document" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#DocumentModal"><i class="fa fa-plus"></i></a>
                            <a class="btn btn-primary btn-circle   btn-edit-Document" title="Edit" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#DocumentModal" disabled="disabled"><i class="fa fa-pencil"></i></a>
                            <a class="btn btn-danger btn-circle   btn-delete-Document" data-toggle="tooltip" data-placement="bottom" title="Delete" disabled="disabled"><i class="fa fa-trash-o"></i> </a>
                            <button title="Refresh" class="btn btn-primary btn-circle   btn-Refresh-Document" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-reply"></i></button>
                            <button title="Clear Sorting" class="btn btn-warning btn-circle   btn-ClearSorting-Document" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-upload"></i></button>
                            <button class="btn btn-danger btn-circle   btn-clearFilter-Document" data-toggle="tooltip" data-placement="bottom" title="Clear Filter"><i class="fa fa-filter"></i></button>
                        </div>
                    }

                    <div class="table-responsive profile-table">
                        <table id="DocumentModalTable" class="table-bordered display table style2 table-striped  dataTable" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Type</th>
                                    <th>Name</th>
                                    <th>Document/Link</th>
                                    <th>Category</th>
                                    <th>Business</th>
                                    <th>Division</th>
                                    <th>Pool</th>
                                    <th>Function</th>
                                    <th>Created Date</th>
                                </tr>
                            </thead>
                            
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr id="@item.Id" class="dataTr">
                                        <td>@item.Type</td>
                                        @if (@item.Type == "Document")
                                        {
                                            <td>@item.Description</td>
                                        }
                                        else if (@item.Type == "Link")
                                        {
                                            <td>@item.LinkDisplayText</td>
                                        }
                                        @if (@item.Type == "Document")
                                        {
                                            <td><a href="~/Upload/AdminDocument/@item.DocumentPath" target="_blank" download="@item.DocumentOriginalPath">@item.DocumentOriginalPath</a></td>
                                        }
                                        else if (@item.Type == "Link")
                                        {
                                            <td><a href="@item.LinkURL" target="_blank">@item.LinkURL</a></td>
                                        }
                                        <td>@item.CategoryName</td>
                                        <td>@item.Business</td>
                                        <td>@item.Division</td>
                                        <td>@item.Pool</td>
                                        <td>@item.Function</td>
                                        <td>@item.CreateDate</td>

                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th><input type="text" class="form-control SearchType" placeholder="Type"></th>
                                    <th><input type="text" class="form-control SearchDescription" placeholder="Description"></th>
                                    <th><input type="text" class="form-control SearchName" placeholder="Document/Link"></th>
                                    <th><input type="text" class="form-control SearchCategory" placeholder="Category"></th>
                                    <th><input type="text" class="form-control SearchBusiness" placeholder="Business"></th>
                                    <th><input type="text" class="form-control SearchDivision" placeholder="Division"></th>
                                    <th><input type="text" class="form-control SearchPool" placeholder="Pool"></th>
                                    <th><input type="text" class="form-control SearchFunction" placeholder="Function"></th>
                                    <th><input type="text" class="form-control SearchCreated" placeholder="Created"></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var AdminconstantDocument =
        {
            Index:'@Url.Action("Index","AdminDocument")',
            Open:'@Url.Action("AddDocument", "AdminDocument")',
            AddEdit: '@Url.Action("SaveDocument", "AdminDocument")',
            ImageData: '@Url.Action("ImageData", "AdminDocument")',
            bindDiv: '@Url.Action("bindDivisionList", "AdminDocument")',
            bindpool: '@Url.Action("bindPoolList", "AdminDocument")',
            bindFuncation: '@Url.Action("bindFuncationList", "AdminDocument")',
            deleteDocument:'@Url.Action("DeleteDocument", "AdminDocument")'
        }
</script>
<script src="~/JS/Admin/AdminDocument/AdminDocumentJS.js"></script>