Models/Settings/CompanyStructureViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HRTool.Models.Settings
{
    public class CompanyStructureViewModel
    {
        public CompanyStructureViewModel()
        {
            businessLists = new List<BusinessViewModel>();
            divisionLists = new List<DivisionViewModel>();
            poolLists = new List<PoolViewModel>();
            functionLists = new List<FunctionViewModel>();

        }
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Archived { get; set; }
        public string UserIDCreatedBy { get; set; }
        public string UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public IList<BusinessViewModel> businessLists { get; set; }
        public IList<DivisionViewModel> divisionLists { get; set; }
        public IList<PoolViewModel> poolLists { get; set; }
        public IList<FunctionViewModel> functionLists { get; set; }

    }

    public class BusinessViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Archived { get; set; }
        public string UserIDCreatedBy { get; set; }
        public string UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
    public class DivisionViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int BusinessID { get; set; }
        public string BusinessName { get; set; }
        public bool Archived { get; set; }
        public string UserIDCreatedBy { get; set; }
        public string UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }

    public class PoolViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int BusinessID { get; set; }
        public string BusinessName { get; set; }
        public int DivisionID { get; set; }
        public string DivisionName { get; set; }
        public bool Archived { get; set; }
        public string UserIDCreatedBy { get; set; }
        public string UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }


    }

    public class FunctionViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int BusinessID { get; set; }
        public string BusinessName { get; set; }
        public int DivisionID { get; set; }
        public string DivisionName { get; set; }
        public bool Archived { get; set; }
        public string UserIDCreatedBy { get; set; }
        public string UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }

    }
}

Controllers/CompanyStructureController.cs
using HRTool.CommanMethods.Settings;
using HRTool.DataModel;
using HRTool.Models.Settings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Microsoft.AspNet.Identity;
using HRTool.CommanMethods;

namespace HRTool.Controllers
{
    [CustomAuthorize]
    public class CompanyStructureController : Controller
    {
        #region Constant
        EvolutionEntities _db = new EvolutionEntities();
        // OtherSettingMethod _otherSettingMethod = new OtherSettingMethod();
        CompanyStructureMethod _CompanyStructureMethod = new CompanyStructureMethod();

        #endregion

        #region View

        // GET: /CompanyStructure/
        public ActionResult Index()
        {
            return View();
        }

        #endregion

        #region Business Method
        public CompanyStructureViewModel returnList()
        {
            CompanyStructureViewModel model = new CompanyStructureViewModel();
            var listData = _CompanyStructureMethod.getAllBusinessList();
            foreach (var item in listData)
            {
                BusinessViewModel tableModel = new BusinessViewModel();
                tableModel.Id = item.Id;
                tableModel.Name = item.Name;
                tableModel.CreatedDate = item.CreatedDate;
                tableModel.Archived = item.Archived;
                model.businessLists.Add(tableModel);
            }
            return model;
        }

        public ActionResult businessList()
        {
            CompanyStructureViewModel model = returnList();
            return PartialView("_partialBusinessList", model);
        }

        public ActionResult addBusinessList(string Name, int Id)
        {

            var data = _CompanyStructureMethod.SaveBusinessData(Name, Id, SessionProxy.UserId);
            if (!data)
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
            else
            {
                CompanyStructureViewModel model = returnList();
                return PartialView("_partialBusinessList", model);
            }

        }

        public ActionResult editBusinessName(int Id)
        {

            var data = _CompanyStructureMethod.getBusinessListById(Id);

            if (data == null)
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(data, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult deleteBusiness(int Id)
        {
            var data = _CompanyStructureMethod.deleteBusiness(Id, SessionProxy.UserId);

            if (!data)
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
            else
            {
                // return Json(data, JsonRequestBehavior.AllowGet);
                CompanyStructureViewModel model = returnList();
                return PartialView("_partialBusinessList", model);
            }
        }

        #endregion

        #region Division Method

        public CompanyStructureViewModel returndivList()
        {
            CompanyStructureViewModel model = new CompanyStructureViewModel();
            var listData = _CompanyStructureMethod.getAllDivisionList();
            var listbiz = _CompanyStructureMethod.getAllBusinessList();

            foreach (var item in listData)
            {
                var bizName = _CompanyStructureMethod.getBusinessListById(item.BusinessID);
                if (bizName != null)
                {
                    DivisionViewModel tableModel = new DivisionViewModel();
                    tableModel.Id = item.Id;
                    tableModel.Name = item.Name;
                    tableModel.BusinessName = bizName.Name;
                    tableModel.CreatedDate = item.CreatedDate;
                    tableModel.Archived = item.Archived;
                    model.divisionLists.Add(tableModel);
                }
            }
            foreach (var item in listbiz)
            {
                
                    BusinessViewModel tableModel = new BusinessViewModel();
                    tableModel.Id = item.Id;
                    tableModel.Name = item.Name;
                    tableModel.CreatedDate = item.CreatedDate;
                    tableModel.Archived = item.Archived;
                    model.businessLists.Add(tableModel);
            }

            return model;
        }
        public ActionResult divisionList()
        {
            CompanyStructureViewModel model = returndivList();
            return PartialView("_partialDivisionList", model);
        }

        public ActionResult addDivisionList(string Name, int Id, int businessId)
        {
            var data = _CompanyStructureMethod.SaveDivisionData(Name, Id, businessId, SessionProxy.UserId);
            if (!data)
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
            else
            {
                CompanyStructureViewModel model = returndivList();
                return PartialView("_partialDivisionList", model);
            }


        }

        public ActionResult editDivisionName(int Id)
        {
            DivisionViewModel model = new DivisionViewModel();
            var data = _CompanyStructureMethod.getDivisionById(Id);
            var bizName = _CompanyStructureMethod.getBusinessListById(data.BusinessID);
            model.Id = data.Id;
            model.Name = data.Name;
            model.BusinessID = data.BusinessID;
            model.BusinessName = bizName.Name;
            if (data == null)
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(model, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult deleteDivision(int Id)
        {
            var data = _CompanyStructureMethod.deleteDivision(Id, SessionProxy.UserId);

            if (!data)
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
            else
            {
                CompanyStructureViewModel model = returndivList();
                return PartialView("_partialDivisionList", model);
            }
        }

        #endregion

        #region Pool Method

        public CompanyStructureViewModel returndPoolList()
        {
            CompanyStructureViewModel model = new CompanyStructureViewModel();
            var listpol = _CompanyStructureMethod.getAllPoolsList();
            var listData = _CompanyStructureMethod.getAllDivisionList();
            var listbiz = _CompanyStructureMethod.getAllBusinessList();

            foreach (var item in listpol)
            {
                var bizsName = _CompanyStructureMethod.getBusinessListById((int)item.BusinessID);

                if (bizsName != null)
                {
                    var divName = _CompanyStructureMethod.getDivisionById(item.DivisionID);
                    if (divName != null)
                    {
                        PoolViewModel tablepool = new PoolViewModel();
                        tablepool.Id = item.Id;
                        tablepool.Name = item.Name;
                        tablepool.DivisionName = divName.Name;
                        tablepool.BusinessName = bizsName.Name;
                        tablepool.CreatedDate = item.CreatedDate;
                        model.poolLists.Add(tablepool);
                    }
                    else
                    {
                        PoolViewModel tablepool = new PoolViewModel();
                        tablepool.Id = item.Id;
                        tablepool.Name = item.Name;
                        tablepool.DivisionName = "";
                        tablepool.BusinessName = bizsName.Name;
                        tablepool.CreatedDate = item.CreatedDate;
                        model.poolLists.Add(tablepool);


                    }
                }


            }

            foreach (var item in listData)
            {
                DivisionViewModel tableModel = new DivisionViewModel();
                tableModel.Id = item.Id;
                tableModel.Name = item.Name;
                tableModel.BusinessID = item.BusinessID;
                tableModel.CreatedDate = item.CreatedDate;
                tableModel.Archived = item.Archived;
                model.divisionLists.Add(tableModel);

            }
            foreach (var item in listbiz)
            {
                BusinessViewModel tableModel = new BusinessViewModel();
                tableModel.Id = item.Id;
                tableModel.Name = item.Name;
                tableModel.CreatedDate = item.CreatedDate;
                tableModel.Archived = item.Archived;
                model.businessLists.Add(tableModel);
            }

            return model;
        }

        public ActionResult poolList()
        {
            CompanyStructureViewModel model = returndPoolList();
            return PartialView("_partialPoolList", model);
        }

        public ActionResult bindDivisionList(int businessId)
        {
            var data = _CompanyStructureMethod.GetDivisionListByBizId(businessId);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult addPoolList(string Name, int Id, int businessId, int divisionId)
        {
            var data = _CompanyStructureMethod.SavePoolData(Name, Id, businessId, divisionId, SessionProxy.UserId);
            if (!data)
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
            else
            {
                CompanyStructureViewModel model = returndPoolList();
                return PartialView("_partialPoolList", model);
            }

        }

Views/CompanyStructure/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_SettingLayout.cshtml";
}

<div id="page_content_inner">
    <br />
    <h4 class="heading_a uk-margin-bottom">
        <div class="titletext">
            <h1 class="page-title">
                Business List
                <small>View businesses or create a new one.</small>
            </h1>
            </div>


            <div class="clsDivion hide">
                Division List
                <p>View division or create a new one for business.</p>
            </div>
            <div class="clsPool hide">
                Pool List
                <p>View pools or create a new one.</p>
            </div>
            <div class="clsFunction hide">
                Function List
                <p>View functions or create a new one.</p>
            </div>
         

        <div class="clearfix"></div>
    </h4>
    <button class="btn btn-primary btn-businessList">BUSINESS</button>
    <button class="btn btn-divisionList">DIVISION</button>
    <button class="btn btn-poolList">POOL</button>
    <button class="btn btn-functionList">Function</button>
    <br />
    <br />
    <div class="md-card">
        <div >
            <div id="tableDiv">
                @Html.Action("businessList", "CompanyStructure")
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var constant = {
        BizList: '@Url.Action("businessList", "CompanyStructure")',
        DivList: '@Url.Action("divisionList", "CompanyStructure")',
        PolList: '@Url.Action("poolList", "CompanyStructure")',
        FunList: '@Url.Action("functionList", "CompanyStructure")',
        AddBiz: '@Url.Action("addBusinessList", "CompanyStructure")',
        AddDiv: '@Url.Action("addDivisionList", "CompanyStructure")',
        AddPol: '@Url.Action("addPoolList", "CompanyStructure")',
        AddFun: '@Url.Action("addFunctionList", "CompanyStructure")',
        bindDiv: '@Url.Action("bindDivisionList", "CompanyStructure")',
        EditBiz: '@Url.Action("editBusinessName", "CompanyStructure")',
        DeleteBiz: '@Url.Action("deleteBusiness", "CompanyStructure")',
        EditDiv: '@Url.Action("editDivisionName", "CompanyStructure")',
        DeleteDiv: '@Url.Action("deleteDivision", "CompanyStructure")',
        EditPol: '@Url.Action("editPoolName", "CompanyStructure")',
        DeletePol: '@Url.Action("deletePool", "CompanyStructure")',
        EditFun: '@Url.Action("editFunctionName", "CompanyStructure")',
        DeleteFun: '@Url.Action("deleteFunction", "CompanyStructure")'
    };

</script>

<script src="~/JS/Settings/CompanyStructure/CompanyStuctureJS.js"></script>

Views/CompanyStructure/_partialBusinessList.cshtml
@model HRTool.Models.Settings.CompanyStructureViewModel

<div class="table-btns">
    <a class="btn btn-success btn-circle  " data-toggle="modal" data-target="#addBusiness" onclick="btnaddbusiness()" title="Add Business"><i class="fa fa-plus"></i></a>
    <a class="btn btn-primary btn-circle  btn-edit-business" data-toggle="modal" data-target="#addBusiness" title="Edit" disabled="disabled"><i class="fa fa-pencil"></i></a>
    <a class="btn btn-danger btn-circle  btn-delete-business" title="Delete" disabled="disabled">
        <i class="fa fa-trash-o"></i>
    </a>
</div>
<table id="example" class="table-bordered display table style2 table-striped  dataTable" cellspacing="0">
    <thead>
        <tr>
            <th>Business Name</th>
            <th>Created</th>
        </tr>
    </thead>   
    <tbody>
        @foreach (var item in Model.businessLists)
        {
            <tr id="@item.Id" class="dataTr">
                <td>@item.Name</td>
                <td>@item.CreatedDate</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th><input type="text" class="form-control SearchName" placeholder="Name"></th>
            <th><input type="text" class="form-control SearchCreatedDate" placeholder="Created Date"></th>
        </tr>
    </tfoot>
</table>

<!-- Modal -->
<div class="modal fade" id="addBusiness" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title businessTitle" id="myModalLabel">
                </h4>
            </div>

            <!-- Modal Body -->
            <div class="modal-body">
                <div class="row marbot10">
                    <div class="col-md-2">
                        <label class="control-label" for="BusinessName">Business Name*</label>
                    </div>
                    <div class="col-md-6">
                        <input type="hidden" id="business_Id" />
                        <input type="text" class="form-control" id="businessText" data-toggle="tooltip" data-placement="right" name="BusinessName" title="Business Name" required>
                    </div>
                    <div class="col-md-4">
                        <span class="field-validation-error" id="lbl-error-BusinessName" style="display:none;" data-valmsg-for="BusinessName" data-valmsg-replace="true">The Business Name is required.</span>
                        <span class="field-validation-error" id="lbl-error-BusinessNameExist" style="display:none;" data-valmsg-for="BusinessName" data-valmsg-replace="true">This Business Name is AllReady Exist.</span>
                    </div>
                </div>
            </div>
            <br />
            <!-- Modal Footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-success" id="btn-submit-Business">ADD</button>
                <button type="button" class="btn btn-warning" data-dismiss="modal">CANCEL</button>
            </div>
        </div>
    </div>
</div>

<script>
    DataTableDesignBussiness();
    function DataTableDesignBussiness() {
        $('#example tfoot tr').appendTo('#example thead');
        var table = $("#example").DataTable({
            "sDom": '<"top"i>rt<"bottom"flp><"clear">',
            "scrollX": true
        });
        $("#tableDiv").find(".dataTables_filter").hide();
        $("#tableDiv").find(".dataTables_info").hide();
        $("#tableDiv thead .SearchName").keyup(function () {
            table.column(0).search(this.value).draw();
        });  
        $("#tableDiv thead .SearchCreatedDate").Zebra_DatePicker({
            //direction: false,
            showButtonPanel: false,
            format: 'd-m-Y',
            default_position: 'below',
            onSelect: function () {
                var date = $("#tableDiv").find('.SearchCreatedDate').val();
                table.column(1).search(date).draw();
            }
        });
        $(".dp_clear").on('click', function () {
            var date = $("#tableDiv").find("thead").find('.SearchCreatedDate').val();
            table.column(1).search(date).draw();
        });
    }

</script>

Views/CompanyStructure/_partialDivisionList.cshtml
@model HRTool.Models.Settings.CompanyStructureViewModel

<div class="table-btns">
    <a class="btn btn-success btn-circle " data-toggle="modal" data-target="#addDivision" onclick="btnadddivision()" title="Add Division"><i class="fa fa-plus"></i></a>
    <a class="btn btn-primary btn-circle  btn-edit-division" data-toggle="modal" data-target="#addDivision" title="Edit" disabled="disabled"><i class="fa fa-pencil"></i></a>
    <a class="btn btn-danger btn-circle  btn-delete-division" title="Delete" disabled="disabled">
        <i class="fa fa-trash-o"></i>
    </a>
</div>

<table id="example" class="table-bordered display table style2 table-striped  dataTable" cellspacing="0">
    <thead>
        <tr>
            <th>Division Name</th>
            <th>Business</th>
            <th>Created</th>
        </tr>
    </thead>    
    <tbody>
        @foreach (var items in Model.divisionLists)
        {
            <tr id="@items.Id" class="dataTr">
                <td>@items.Name</td>
                <td>@items.BusinessName</td>
                <td>@items.CreatedDate</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th><input type="text" class="form-control SearchName" placeholder="Name"></th>
            <th><input type="text" class="form-control SearchBussinessName" placeholder="Name"></th>
            <th><input type="text" class="form-control SearchCreatedDate" placeholder="Created Date"></th>
        </tr>
    </tfoot>
</table>

<div class="modal fade" id="addDivision" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true" style="width:100%;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title divisionTitle" id="myModalLabel">
                </h4>
            </div>

            <!-- Modal Body -->
            <div class="modal-body">
               

                <div class="row marbot10">
                    <div class="col-md-2">
                        <label class="control-label" for="BusinessNameList">Business Name*</label>
                    </div>
                    <div class="col-md-6">
                        <select id="selBus" title="Select Business..." class="form-control">
                            <option class="selBusiness" id="0" value="0">-- Select Business --</option>
                            @foreach (var items in Model.businessLists)
                            {
                                <option class="selBusiness" id="1_@items.Id" value="@items.Id">@items.Name</option>
                            }
                        </select>
                    </div>
                    <div class="col-md-4">
                        <span class="field-validation-error" id="lbl-error-BusinessNameList" style="display:none;" data-valmsg-for="BusinessNameList" data-valmsg-replace="true">The Business Name is required.</span>
                       
                    </div>
                </div>

                <div class="row marbot10">
                    <div class="col-md-2">
                        <label class="control-label" for="DivisionName"> Division Name*</label>
                    </div>
                    <div class="col-md-6">
                        <input type="hidden" id="division_Id" />
                        <input type="text" class="form-control" id="divisionText" data-toggle="tooltip" name="DivisionName" title="Division Name" required>
                    </div>
                    <div class="col-md-4">
                        <span class="field-validation-error" id="lbl-error-DivisionName" style="display:none;" data-valmsg-for="DivisionName" data-valmsg-replace="true">The Division Name is required.</span>
                        <span class="field-validation-error" id="lbl-error-DivisionNameExist" style="display:none;" data-valmsg-for="DivisionName" data-valmsg-replace="true">Division name already exist in selected Business.</span>
                     </div>
                </div>
            </div>

            <!-- Modal Footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-success" id="btn-submit-Division">ADD</button>
                <button type="button" class="btn btn-warning" data-dismiss="modal">CANCEL</button>
            </div>
        </div>
    </div>
</div>

<script>
    DataTableDesignDivision();
    function DataTableDesignDivision() {
        $('#example tfoot tr').appendTo('#example thead');
        var table = $("#example").DataTable({
            "sDom": '<"top"i>rt<"bottom"flp><"clear">',
            "scrollX": true
        });
        $("#example").find(".dataTables_filter").hide();
        $("#example").find(".dataTables_info").hide();
        $("#tableDiv thead .SearchName").keyup(function () {
            table.column(0).search(this.value).draw();
        });
        $("#tableDiv thead .SearchBussinessName").keyup(function () {
            table.column(1).search(this.value).draw();
        })
        
        $("#tableDiv thead .SearchCreatedDate").Zebra_DatePicker({
            //direction: false,
            showButtonPanel: false,
            format: 'd-m-Y',
            default_position: 'below',
            onSelect: function () {
                var date = $("#tableDiv").find('.SearchCreatedDate').val();
                table.column(2).search(date).draw();
            }
        });

        $(".dp_clear").on('click', function () {
            var date = $("#tableDiv").find("thead").find('.SearchCreatedDate').val();
            table.column(2).search(date).draw();
        });
    }
</script>