Models/Resources/EmployeeDocumentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRTool.Models.Resources
{
    public class EmployeeDocumentViewModel
    {
        public EmployeeDocumentViewModel()
        {
            BusinessList = new List<SelectListItem>();
            DivisionList = new List<SelectListItem>();
            PoolList = new List<SelectListItem>();
            FunctionList = new List<SelectListItem>();
            CategoryList = new List<SelectListItem>();
            WorkerList = new List<SelectListItem>();
            ManagerList = new List<SelectListItem>();
            CustomerList = new List<SelectListItem>();
        }
        public string Type { get; set; }
        public int Id { get; set; }
        public int EmployeeID { get; set; }
        public string DocumentPath { get; set; }
        public string DocumentOriginalPath { get; set; }
        public string Description { get; set; }
        public string LinkDisplayText { get; set; }
        public string LinkURL { get; set; }
        public int BusinessID { get; set; }
        public string Business { get; set; }
        public int DivisionID { get; set; }
        public string Division { get; set; }
        public int PoolID { get; set; }
        public string Pool { get; set; }
        public int FunctionID { get; set; }
        public string Function { get; set; }
        public int Category { get; set; }
        public string CategoryName { get; set; }
        public bool EmployeeAccess { get; set; }
        public bool ManagerAccess { get; set; }
        public bool CustomerAccess { get; set; }
        public bool SpecificWorker { get; set; }
        public string SpecificWorkerName { get; set; }
        public string WorkerID { get; set; }
        public string SpecificManagerName { get; set; }
        public bool SpecificManager { get; set; }
        public string ManagerID { get; set; }
        public bool SpecificCustomer { get; set; }
        public string SpecificCustomerName { get; set; }
        public string CustomerID { get; set; }
        public bool SignatureRequire { get; set; }
        public string Signature { get; set; }
        public bool Signed { get; set; }
        public string IpAddress { get; set; }
        public string LoginUserID { get; set; }
        public string CreateDate { get; set; }
        public IList<SelectListItem> BusinessList { get; set; }
        public IList<SelectListItem> DivisionList { get; set; }
        public IList<SelectListItem> PoolList { get; set; }
        public IList<SelectListItem> FunctionList { get; set; }
        public IList<SelectListItem> CategoryList { get; set; }
        public IList<SelectListItem> WorkerList { get; set; }
        public IList<SelectListItem> ManagerList { get; set; }
        public IList<SelectListItem> CustomerList { get; set; }
    }

    public class EmployeeDocumentListModel 
    {
        public EmployeeDocumentListModel()
        {
            EmployeeList = new List<EmployeeDocumentViewModel>();
        }

        //public string LoginUserID { get; set; }
        public int EmployeeID { get; set; }
        public IList<EmployeeDocumentViewModel> EmployeeList { get; set; }
    }

   
}

Controllers/EmployeeDocumentController.cs
using HRTool.CommanMethods.Admin;
using HRTool.CommanMethods.Resources;
using HRTool.CommanMethods.RolesManagement;
using HRTool.CommanMethods.Settings;
using HRTool.DataModel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Configuration;
using System.IO;
using HRTool.Models.Resources;
using HRTool.CommanMethods;
using static HRTool.CommanMethods.Enums;

namespace HRTool.Controllers
{
    [CustomAuthorize]
    public class EmployeeDocumentController : Controller
    {
        #region Constant

        EvolutionEntities _db = new EvolutionEntities();
        EmployeeDocumentMethod _EmployeeDocument = new EmployeeDocumentMethod();
        OtherSettingMethod _otherSettingMethod = new OtherSettingMethod();
        EmployeeMethod _employeeMethod = new EmployeeMethod();
        CompanyStructureMethod _CompanyStructureMethod = new CompanyStructureMethod();
        AdminTMSMethod _AdminTMSMethod = new AdminTMSMethod();
        TMSSettingsMethod _TMSSettingsMethod = new TMSSettingsMethod();
        RolesManagementMethod _RolesManagementMethod = new RolesManagementMethod();

        #endregion

        // GET: /EmployeeDocument/
        [Authorize]
        public ActionResult Index(int EmployeeId)
        {
            EmployeeDocumentListModel model = new EmployeeDocumentListModel();
            //model.LoginUserID = SessionProxy.UserId;
            model.EmployeeID = EmployeeId;
            var data = _EmployeeDocument.getDocumentDetailsByEmployeeId(EmployeeId);
            if (data.Count > 0)
            {
                foreach (var details in data)
                {
                    if (!string.IsNullOrEmpty(details.DocumentPath) || !string.IsNullOrEmpty(details.Description))
                    {
                        EmployeeDocumentViewModel datamodel = new EmployeeDocumentViewModel();
                        datamodel.Type = "Document";
                        datamodel.Id = details.Id;
                        datamodel.EmployeeID = details.EmployeeID;
                        // datamodel.LoginUserID = SessionProxy.UserId;
                        datamodel.Description = details.Description;
                        datamodel.DocumentOriginalPath = details.DocumentOriginalPath;
                        datamodel.DocumentPath = details.DocumentPath;
                        datamodel.Category = (int)details.Category;
                        if (details.Category != 0)
                        {
                            var res = _otherSettingMethod.getSystemListValueById((int)details.Category);
                            datamodel.CategoryName = res.Value;
                        }
                        datamodel.BusinessID = (int)details.BusinessID;
                        if (details.BusinessID != 0)
                        {
                            var buz = _CompanyStructureMethod.getBusinessListById((int)details.BusinessID);
                            if (buz != null)
                            {
                                datamodel.Business = buz.Name;
                            }
                        }
                        datamodel.DivisionID = (int)details.DivisionID;
                        if (details.DivisionID != 0)
                        {
                            var div = _CompanyStructureMethod.getDivisionById((int)details.DivisionID);
                            if (div != null)
                            {
                                datamodel.Division = div.Name;
                            }
                        }
                        datamodel.PoolID = (int)details.PoolID;
                        if (details.PoolID != 0)
                        {
                            var pol = _CompanyStructureMethod.getPoolsListById((int)details.PoolID);
                            if (pol != null)
                            {
                                datamodel.Pool = pol.Name;
                            }
                        }
                        datamodel.FunctionID = (int)details.FunctionID;
                        if (details.FunctionID != 0)
                        {
                            var fun = _CompanyStructureMethod.getFunctionsListById((int)details.FunctionID);
                            if (fun != null)
                            {
                                datamodel.Function = fun.Name;
                            }
                        }
                        datamodel.CreateDate = String.Format("{0:dd-MM-yyyy}", details.CreatedDate);
                        datamodel.SignatureRequire = details.SignatureRequire;
                        if (details.SignatureRequire == true)
                        {
                            datamodel.Signature = "YES";
                        }
                        else
                        {
                            datamodel.Signature = "NO";
                        }
                        var SigCount = _EmployeeDocument.getDocumentSignatureListByDocumentId(details.Id);
                        if (SigCount != null)
                        {
                            datamodel.Signed = true;
                        }
                        else
                        {
                            datamodel.Signed = false;

                        }
                        model.EmployeeList.Add(datamodel);
                    }
                    else if(!string.IsNullOrEmpty(details.LinkDisplayText) || !string.IsNullOrEmpty(details.LinkURL))
                    {
                             EmployeeDocumentViewModel datamodel = new EmployeeDocumentViewModel();
                            datamodel.Type = "Link";
                            datamodel.Id = details.Id;
                            datamodel.EmployeeID = details.EmployeeID;
                            // datamodel.LoginUserID = SessionProxy.UserId;
                            datamodel.LinkDisplayText = details.LinkDisplayText;
                            datamodel.LinkURL = details.LinkURL;
                            datamodel.Category = (int)details.Category;
                            if (details.Category != 0)
                            {
                                var res = _otherSettingMethod.getSystemListValueById((int)details.Category);
                                datamodel.CategoryName = res.Value;
                            }
                            datamodel.BusinessID = (int)details.BusinessID;
                            if (details.BusinessID != 0)
                            {
                                var buz = _CompanyStructureMethod.getBusinessListById((int)details.BusinessID);
                                if (buz != null)
                                {
                                    datamodel.Business = buz.Name;
                                }
                            }
                            datamodel.DivisionID = (int)details.DivisionID;
                            if (details.DivisionID != 0)
                            {
                                var div = _CompanyStructureMethod.getDivisionById((int)details.DivisionID);
                                if (div != null)
                                {
                                    datamodel.Division = div.Name;
                                }
                            }
                            datamodel.PoolID = (int)details.PoolID;
                            if (details.PoolID != 0)
                            {
                                var pol = _CompanyStructureMethod.getPoolsListById((int)details.PoolID);
                                if (pol != null)
                                {
                                    datamodel.Pool = pol.Name;
                                }
                            }
                            datamodel.FunctionID = (int)details.FunctionID;
                            if (details.FunctionID != 0)
                            {
                                var fun = _CompanyStructureMethod.getFunctionsListById((int)details.FunctionID);
                                if (fun != null)
                                {
                                    datamodel.Function = fun.Name;
                                }
                            }
                            datamodel.CreateDate = String.Format("{0:dd-MM-yyyy}", details.CreatedDate);
                            datamodel.SignatureRequire = details.SignatureRequire;
                            if (details.SignatureRequire == true)
                            {
                                datamodel.Signature = "YES";
                            }
                            else
                            {
                                datamodel.Signature = "NO";
                            }
                            var SigCount = _EmployeeDocument.getDocumentSignatureListByDocumentId(details.Id);
                            if (SigCount != null)
                            {
                                datamodel.Signed = true;
                            }
                            else
                            {
                                datamodel.Signed = false;

                            }
                            model.EmployeeList.Add(datamodel);
                        }
                    }
                
            }
            return View(model);

        }

        public EmployeeDocumentViewModel returnList(int Id, int EmployeeID)
        {
            EmployeeDocumentViewModel datamodel = new EmployeeDocumentViewModel();

            foreach (var item in _otherSettingMethod.getAllSystemValueListByKeyName("Document Type"))
            {

Views/EmployeeDocument/Index.cshtml
@model HRTool.Models.Resources.EmployeeDocumentListModel
@{
       Layout = "~/Views/Shared/_ResourcesLayout.cshtml";
}

<div id="DocumentModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title DocumentTitle">Add Document</h4>
            </div>
            <div class="modal-body" align="right" id="AddDocumentBody">

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success btn-Add-Edit" id="btn-submit-Document">Add</button>
                <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<div id="DocumentSignatureModal" class="modal fade signature-popup-main" role="dialog">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title DocumentSignatureTitle">Employee Signature</h4>
            </div>
            <div class="modal-body" align="right" id="AddSignatureBody">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning btn-Signature-Close" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success btn-Signature-Edit" id="btn-submit-Signature">Sign</button>
            </div>
        </div>

    </div>
</div>

<h1 class="page-title">
    Document List
    <small>View company documents or upload a new one.</small>
</h1>

 
     
           
                <div id="tableDiv">
                    <input type="hidden" id="Employee_ID" value="@Model.EmployeeID" />
                    <div class="table-btns">
                        <a class="btn btn-success btn-circle  btn-add-Document" title="Add Document" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#DocumentModal"><i class="fa fa-plus"></i></a>
                        <a class="btn btn-primary btn-circle  btn-edit-Document" title="Edit" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#DocumentModal" disabled="disabled"><i class="fa fa-pencil"></i></a>
                        <a class="btn btn-danger btn-circle  btn-delete-Document" data-toggle="tooltip" data-placement="bottom" title="Delete" disabled="disabled"><i class="fa fa-trash-o"></i> </a>
                        <button title="Refresh" class="btn btn-primary btn-circle  btn-Refresh-Document" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-reply"></i></button>
                        <button title="Clear Sorting" class="btn btn-warning btn-circle  btn-ClearSorting-Document" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-upload"></i></button>
                        <button class="btn btn-info btn-circle  btn-clearFilter-Document" data-toggle="tooltip" data-placement="bottom" title="Clear Filter"><i class="fa fa-filter"></i></button>
                    </div>
                    <div class="table-responsive">
                        <table id="DocumentModalTable" class="table-bordered display table style2 table-striped  dataTable" cellspacing="0">
                            <thead>
                                <tr class="tblHeading">
                                    <th>Type</th>
                                    <th>Name</th>
                                    <th>Document/Link</th>
                                    <th>Category</th>
                                    <th>Business</th>
                                    <th>Division</th>
                                    <th>Pool</th>
                                    <th>Function</th>
                                    <th>Created Date</th>
                                    <th>Sign</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.EmployeeList)
                                {
                                    <tr id="@item.Id" class="dataTr">
                                        <td>@item.Type</td>
                                        @if (@item.Type == "Document")
                                        {
                                            <td>@item.Description</td>
                                        }
                                        else if (@item.Type == "Link")
                                        {
                                            <td>@item.LinkDisplayText</td>
                                        }
                                        @if (@item.Type == "Document")
                                        {
                                            <td><a href="~/Upload/Resources/EmployeeDocument/@item.DocumentPath" target="_blank" download="@item.DocumentOriginalPath">@item.DocumentOriginalPath</a></td>
                                        }
                                        else if (@item.Type == "Link")
                                        {
                                            <td><a href="@item.LinkURL" target="_blank">@item.LinkURL</a></td>
                                        }
                                        <td>@item.CategoryName</td>
                                        <td>@item.Business</td>
                                        <td>@item.Division</td>
                                        <td>@item.Pool</td>
                                        <td>@item.Function</td>
                                        <td>@item.CreateDate</td>
                                        <td>@item.Signature</td>
                                        <td>
                                            @if (item.SignatureRequire == true && item.Signed == false)
                                            {
                                                <button class="btn btn-primary btn-Pending-Signature" onclick="btnPendingSignature(@item.Id)" data-toggle="modal" data-target="#DocumentSignatureModal">Pending</button>
                                            }
                                            @if (item.SignatureRequire == true && item.Signed == true)
                                            {
                                                <button class="btn btn-primary btn-Signed-Signature" onclick="btnSignedSignature(@item.Id)" data-toggle="modal" data-target="#DocumentSignatureModal">Signed</button>

                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th><input type="text" class="form-control" placeholder="Type"></th>
                                    <th><input type="text" class="form-control" placeholder="Description"></th>
                                    <th><input type="text" class="form-control" placeholder="Name"></th>
                                    <th><input type="text" class="form-control" placeholder="Category"></th>
                                    <th><input type="text" class="form-control" placeholder="Business"></th>
                                    <th><input type="text" class="form-control" placeholder="Division"></th>
                                    <th><input type="text" class="form-control" placeholder="Pool"></th>
                                    <th><input type="text" class="form-control" placeholder="Function"></th>
                                    <th><input type="text" class="form-control" placeholder="Created"></th>
                                    <th><input type="text" class="form-control" placeholder="Signature"></th>
                                    <th></th>
                                </tr>
                            </tfoot>                            
                        </table>
                    </div>
            </div>        

<script type="text/javascript">
    var constantDocument =
        {
            Index: '@Url.Action("Index", "EmployeeDocument")',
            Open: '@Url.Action("AddDocument", "EmployeeDocument")',
            AddEdit: '@Url.Action("SaveDocument", "EmployeeDocument")',
            ImageData: '@Url.Action("ImageData", "EmployeeDocument")',
            bindDiv: '@Url.Action("bindDivisionList", "EmployeeDocument")',
            bindpool: '@Url.Action("bindPoolList", "EmployeeDocument")',
            bindFuncation: '@Url.Action("bindFuncationList", "EmployeeDocument")',
            deleteDocument: '@Url.Action("DeleteDocument", "EmployeeDocument")',
            Signature: '@Url.Action("PendingSignature", "EmployeeDocument")',
            SignatureSigned: '@Url.Action("SignedSignature", "EmployeeDocument")',
            SaveSignature:'@Url.Action("SaveSignature", "EmployeeDocument")'
        }
</script>
<script src="~/JS/Resources/Document/EmployeeDocumentJS.js"></script>

Views/EmployeeDocument/_partialAddEmployeeSignature.cshtml
@model HRTool.Models.Resources.EmployeeSignatureViewModel

<input type="hidden" id="Document_ID" value="@Model.DocumentID" />
<input type="hidden" id="Employee_ID" value="@Model.EmployeeID" />
<input type="hidden" id="IpAddress" value="@Model.IpAddress">
<div class="employeeSignature">
    <div class="topContent">
        <label id="lbl_DocumentName">@Model.DocumentName</label>
        <span class="txt_IpAddress">IP : @Model.IpAddress</span>
        <span class="txt_Createdate">@Model.CreateDate</span>
    </div>
    <p>By signing this document you are declaring that you have read and understood the contents contained within.</p>
</div>

<div class="row marbot10">
    <div class="col-md-3">
    </div>
    <div class="col-md-6 Signature_Div" style="width:100%">
        <input type="text" maxlength="30" id="txt_SignatureText" placeholder="Enter Your Name" />
        <textarea  class="textarea-resizeNone" readonly="readonly" id="text_Signature"></textarea>
    </div>
    <div class="col-md-3">
        <span class="field-validation-error" id="lbl-error-SignatureText" style="display:none;" data-valmsg-for="SignatureText" data-valmsg-replace="true">SignatureText  is required.</span>
    </div>
</div>

Views/EmployeeDocument/_partialShowEmployeeSignature.cshtml
@model HRTool.Models.Resources.EmployeeSignatureViewModel

<input type="hidden" id="documentSignature_ID" value="@Model.Id" />
<input type="hidden" id="Document_ID" value="@Model.DocumentID" />
<div class="employeeSignature">
    <div class="topContent">
        <label id="lbl_DocumentName">@Model.DocumentName</label>
        <span class="txt_IpAddress">IP : @Model.IpAddress</span>
        <span class="txt_Createdate">@Model.CreateDate</span>
    </div>

    <p>By signing this document you are declaring that you have read and understood the contents contained within.</p>
</div>
<div class="row marbot10">
    <div class="col-md-3">
    </div>
    <div class="col-md-6 dropdown" style="width:100%">
        <textarea class="textarea-resizeNone" readonly="readonly" id="text_Signature">@Model.SignatureText</textarea>
    </div>
    <div class="col-md-3">
        @*<span class="field-validation-error" id="lbl-error-SignatureText" style="display:none;" data-valmsg-for="SignatureText" data-valmsg-replace="true">SignatureText  is required.</span>*@
    </div>
</div>
 

Views/EmployeeDocument/_partialShowSendSignature.cshtml
@model HRTool.Models.Resources.EmployeeSignatureViewModel

<input type="hidden" id="SignatureID" value="@Model.Id" />

<div class="row marbot10">
    <div class="col-md-3">
    </div>
    <div class="col-md-6 dropdown">
        Invitation to sign document has been sent successfully.
    </div>
    <div class="col-md-3">
        @*<span class="field-validation-error" id="lbl-error-SignatureText" style="display:none;" data-valmsg-for="SignatureText" data-valmsg-replace="true">SignatureText  is required.</span>*@
    </div>
</div>